AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Max: 15

Metrics/ParameterLists:
  Max: 6

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Exclude:
    - "spec/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
